// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Runtime: use pooled connection (DATABASE_URL via PgBouncer port 6543)
    // Migrations: set DATABASE_URL to DIRECT_URL (port 5432) when running migrate
    url: process.env["DATABASE_URL"],
  },
});
